
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var l={},n;for(n in g)g.hasOwnProperty(n)&&(l[n]=g[n]);var t=[],aa="./this.program";function w(a,b){throw b;}var ba=!1,y=!1,z=!1,ca=!1;ba="object"===typeof window;y="function"===typeof importScripts;z="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!ba&&!z&&!y;var A="",da,ea,C,fa,ha;
if(z)A=y?require("path").dirname(A)+"/":__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},C=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),t=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",
D),w=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),C=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?t=scriptArgs:"undefined"!=typeof arguments&&(t=arguments),"function"===typeof quit&&(w=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||y)y?A=self.location.href:"undefined"!==typeof document&&document.currentScript&&(A=document.currentScript.src),A=0!==A.indexOf("blob:")?A.substr(0,A.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(C=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=g.print||console.log.bind(console),E=g.printErr||console.warn.bind(console);for(n in l)l.hasOwnProperty(n)&&(g[n]=l[n]);l=null;g.arguments&&(t=g.arguments);g.thisProgram&&(aa=g.thisProgram);g.quit&&(w=g.quit);var G;g.wasmBinary&&(G=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;
"object"!==typeof WebAssembly&&D("no native wasm support detected");var ka,la=!1;function assert(a,b){a||D("Assertion failed: "+b)}function ma(a){var b=g["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function na(a,b,c,d){var e={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var x=(p.length<<2)+1;r=H(x);oa(p,pa,r,x)}return r},array:function(p){var r=H(p.length);I.set(p,r);return r}},h=ma(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var v=e[c[m]];v?(0===a&&(a=qa()),k[m]=v(d[m])):k[m]=d[m]}c=h.apply(null,k);c=function(p){return"string"===b?ra(p):"boolean"===b?!!p:p}(c);0!==a&&sa(a);return c}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function J(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function ra(a){return a?J(pa,a,void 0):""}
function oa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var m=a.charCodeAt(++h);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function va(a){var b=ua(a)+1,c=H(b);oa(a,I,c,b);return c}var wa,I,pa,xa,K,ya,za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=g.preRun.shift();za.unshift(a)}var L=0,Ea=null,M=null;g.preloadedImages={};g.preloadedAudios={};
function D(a){if(g.onAbort)g.onAbort(a);E(a);la=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Fa(){return N.startsWith("data:application/octet-stream;base64,")}var N="diagon.js-1.1.wasm";if(!Fa()){var Ga=N;N=g.locateFile?g.locateFile(Ga,A):A+Ga}function Ha(){var a=N;try{if(a==N&&G)return new Uint8Array(G);if(C)return C(a);throw"both async and sync fetching of the wasm failed";}catch(b){D(b)}}
function Ia(){if(!G&&(ba||y)){if("function"===typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(ea)return new Promise(function(a,b){ea(N,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}var O,Ja;
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.xa;"number"===typeof c?void 0===b.X?ya.get(c)():ya.get(c)(b.X):c(void 0===b.X?null:b.X)}}}function La(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Ma(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Na(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Oa(a){if("/"===a)return"/";a=Ma(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Pa(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(z)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){D("randomDevice")}}
function Qa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ra=[];function Sa(a,b){Ra[a]={input:[],output:[],O:b};Ta(a,Ua)}
var Ua={open:function(a){var b=Ra[a.node.rdev];if(!b)throw new P(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.O.flush(a.tty)},flush:function(a){a.tty.O.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.O.ga)throw new P(60);for(var e=0,h=0;h<d;h++){try{var k=a.tty.O.ga(a.tty)}catch(m){throw new P(29);}if(void 0===k&&0===e)throw new P(6);if(null===k||void 0===k)break;e++;b[c+h]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.O.Z)throw new P(60);try{for(var e=
0;e<d;e++)a.tty.O.Z(a.tty,b[c+e])}catch(h){throw new P(29);}d&&(a.node.timestamp=Date.now());return e}},Wa={ga:function(a){if(!a.input.length){var b=null;if(z){var c=Buffer.ka?Buffer.ka(256):new Buffer(256),d=0;try{d=fa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Va(b,!0)}return a.input.shift()},Z:function(a,b){null===b||10===b?(ja(J(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(J(a.output,0)),a.output=[])}},Xa={Z:function(a,b){null===b||10===b?(E(J(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(E(J(a.output,0)),a.output=[])}},Q={J:null,L:function(){return Q.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.J||(Q.J={dir:{node:{M:Q.D.M,K:Q.D.K,lookup:Q.D.lookup,S:Q.D.S,rename:Q.D.rename,unlink:Q.D.unlink,rmdir:Q.D.rmdir,readdir:Q.D.readdir,symlink:Q.D.symlink},stream:{N:Q.F.N}},file:{node:{M:Q.D.M,K:Q.D.K},stream:{N:Q.F.N,read:Q.F.read,write:Q.F.write,aa:Q.F.aa,ha:Q.F.ha,ja:Q.F.ja}},link:{node:{M:Q.D.M,K:Q.D.K,readlink:Q.D.readlink},stream:{}},ba:{node:{M:Q.D.M,K:Q.D.K},stream:Ya}});c=Za(a,b,c,d);16384===(c.mode&61440)?(c.D=Q.J.dir.node,
c.F=Q.J.dir.stream,c.C={}):32768===(c.mode&61440)?(c.D=Q.J.file.node,c.F=Q.J.file.stream,c.G=0,c.C=null):40960===(c.mode&61440)?(c.D=Q.J.link.node,c.F=Q.J.link.stream):8192===(c.mode&61440)&&(c.D=Q.J.ba.node,c.F=Q.J.ba.stream);c.timestamp=Date.now();a&&(a.C[b]=c,a.timestamp=c.timestamp);return c},ya:function(a){return a.C?a.C.subarray?a.C.subarray(0,a.G):new Uint8Array(a.C):new Uint8Array(0)},da:function(a,b){var c=a.C?a.C.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,
256)),c=a.C,a.C=new Uint8Array(b),0<a.G&&a.C.set(c.subarray(0,a.G),0))},pa:function(a,b){if(a.G!=b)if(0==b)a.C=null,a.G=0;else{var c=a.C;a.C=new Uint8Array(b);c&&a.C.set(c.subarray(0,Math.min(b,a.G)));a.G=b}},D:{M:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.G:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.la=4096;b.blocks=Math.ceil(b.size/b.la);return b},K:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.pa(a,b.size)},lookup:function(){throw $a[44];},S:function(a,b,c,d){return Q.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ab(b,c)}catch(h){}if(d)for(var e in d.C)throw new P(55);}delete a.parent.C[a.name];a.parent.timestamp=Date.now();a.name=c;b.C[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.C[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=ab(a,b),d;for(d in c.C)throw new P(55);delete a.C[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.C)a.C.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},F:{read:function(a,b,c,d,e){var h=a.node.C;if(e>=a.node.G)return 0;a=Math.min(a.node.G-
e,d);if(8<a&&h.subarray)b.set(h.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=h[e+d];return a},write:function(a,b,c,d,e,h){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.C||a.C.subarray)){if(h)return a.C=b.subarray(c,c+d),a.G=d;if(0===a.G&&0===e)return a.C=b.slice(c,c+d),a.G=d;if(e+d<=a.G)return a.C.set(b.subarray(c,c+d),e),d}Q.da(a,e+d);if(a.C.subarray&&b.subarray)a.C.set(b.subarray(c,c+d),e);else for(h=0;h<d;h++)a.C[e+h]=b[c+h];a.G=Math.max(a.G,e+d);return d},N:function(a,b,
c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.G);if(0>b)throw new P(28);return b},aa:function(a,b,c){Q.da(a.node,b+c);a.node.G=Math.max(a.node.G,b+c)},ha:function(a,b,c,d,e,h){if(0!==b)throw new P(28);if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.C;if(h&2||a.buffer!==wa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;h=16384*Math.ceil(c/16384);for(b=bb(h);c<h;)I[b+c++]=0;c=b;if(!c)throw new P(48);I.set(a,c)}else d=!1,
c=a.byteOffset;return{Aa:c,wa:d}},ja:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);if(e&2)return 0;Q.F.write(a,b,0,d,c,!1);return 0}}},cb=null,db={},R=[],eb=1,S=null,fb=!0,gb={},P=null,$a={};
function T(a,b){a=Qa("/",a);b=b||{};if(!a)return{path:"",node:null};var c={fa:!0,$:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.$)throw new P(32);a=La(a.split("/").filter(function(k){return!!k}),!1);var e=cb;c="/";for(d=0;d<a.length;d++){var h=d===a.length-1;if(h&&b.parent)break;e=ab(e,a[d]);c=Ma(c+"/"+a[d]);e.T&&(!h||h&&b.fa)&&(e=e.T.root);if(!h||b.ea)for(h=0;40960===(e.mode&61440);)if(e=hb(c),c=Qa(Na(c),e),e=T(c,{$:b.$}).node,40<h++)throw new P(32);}return{path:c,node:e}}
function ib(a){for(var b;;){if(a===a.parent)return a=a.L.ia,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function ab(a,b){var c;if(c=(c=kb(a,"x"))?c:a.D.lookup?0:2)throw new P(c,a);for(c=S[jb(a.id,b)];c;c=c.oa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.D.lookup(a,b)}
function Za(a,b,c,d){a=new lb(a,b,c,d);b=jb(a.parent.id,a.name);a.oa=S[b];return S[b]=a}var mb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function kb(a,b){if(fb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ob(a,b){try{return ab(a,b),20}catch(c){}return kb(a,"wx")}
function pb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!R[a])return a;throw new P(33);}function qb(a,b,c){rb||(rb=function(){},rb.prototype={});var d=new rb,e;for(e in a)d[e]=a[e];a=d;b=pb(b,c);a.fd=b;return R[b]=a}var Ya={open:function(a){a.F=db[a.node.rdev].F;a.F.open&&a.F.open(a)},N:function(){throw new P(70);}};function Ta(a,b){db[a]={F:b}}
function sb(a,b){var c="/"===b,d=!b;if(c&&cb)throw new P(10);if(!c&&!d){var e=T(b,{fa:!1});b=e.path;e=e.node;if(e.T)throw new P(10);if(16384!==(e.mode&61440))throw new P(54);}b={type:a,za:{},ia:b,na:[]};a=a.L(b);a.L=b;b.root=a;c?cb=a:e&&(e.T=b,e.L&&e.L.na.push(b))}function tb(a,b,c){var d=T(a,{parent:!0}).node;a=Oa(a);if(!a||"."===a||".."===a)throw new P(28);var e=ob(d,a);if(e)throw new P(e);if(!d.D.S)throw new P(63);return d.D.S(d,a,b,c)}function U(a){return tb(a,16895,0)}
function ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);tb(a,b|8192,c)}function vb(a,b){if(!Qa(a))throw new P(44);var c=T(b,{parent:!0}).node;if(!c)throw new P(44);b=Oa(b);var d=ob(c,b);if(d)throw new P(d);if(!c.D.symlink)throw new P(63);c.D.symlink(c,b,a)}function hb(a){a=T(a).node;if(!a)throw new P(44);if(!a.D.readlink)throw new P(28);return Qa(ib(a.parent),a.D.readlink(a))}
function V(a,b,c,d,e){if(""===a)throw new P(44);if("string"===typeof b){var h=mb[b];if("undefined"===typeof h)throw Error("Unknown file open mode: "+b);b=h}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var k=a;else{a=Ma(a);try{k=T(a,{ea:!(b&131072)}).node}catch(m){}}h=!1;if(b&64)if(k){if(b&128)throw new P(20);}else k=tb(a,c,0),h=!0;if(!k)throw new P(44);8192===(k.mode&61440)&&(b&=-513);if(b&65536&&16384!==(k.mode&61440))throw new P(54);if(!h&&(c=k?40960===(k.mode&61440)?
32:16384===(k.mode&61440)&&("r"!==nb(b)||b&512)?31:kb(k,nb(b)):44))throw new P(c);if(b&512){c=k;c="string"===typeof c?T(c,{ea:!0}).node:c;if(!c.D.K)throw new P(63);if(16384===(c.mode&61440))throw new P(31);if(32768!==(c.mode&61440))throw new P(28);if(h=kb(c,"w"))throw new P(h);c.D.K(c,{size:0,timestamp:Date.now()})}b&=-131713;d=qb({node:k,path:ib(k),flags:b,seekable:!0,position:0,F:k.F,va:[],error:!1},d,e);d.F.open&&d.F.open(d);!g.logReadFiles||b&1||(wb||(wb={}),a in wb||(wb[a]=1,E("FS.trackingDelegate error on read file: "+
a)));try{gb.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),gb.onOpenFile(a,e))}catch(m){E("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function xb(a){if(null===a.fd)throw new P(8);a.Y&&(a.Y=null);try{a.F.close&&a.F.close(a)}catch(b){throw b;}finally{R[a.fd]=null}a.fd=null}function yb(a,b,c){if(null===a.fd)throw new P(8);if(!a.seekable||!a.F.N)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.F.N(a,b,c);a.va=[]}
function Ab(){P||(P=function(a,b){this.node=b;this.qa=function(c){this.I=c};this.qa(a);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(function(a){$a[a]=new P(a);$a[a].stack="<generic error, no stack>"}))}var Bb;function Cb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function W(a,b,c){a=Ma("/dev/"+a);var d=Cb(!!b,!!c);Db||(Db=64);var e=Db++<<8|0;Ta(e,{open:function(h){h.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(h,k,m,v){for(var p=0,r=0;r<v;r++){try{var x=b()}catch(F){throw new P(29);}if(void 0===x&&0===p)throw new P(6);if(null===x||void 0===x)break;p++;k[m+r]=x}p&&(h.node.timestamp=Date.now());return p},write:function(h,k,m,v){for(var p=0;p<v;p++)try{c(k[m+p])}catch(r){throw new P(29);}v&&(h.node.timestamp=Date.now());return p}});
ub(a,d,e)}var Db,X={},rb,wb,Eb=void 0;function Y(){Eb+=4;return K[Eb-4>>2]}function Z(a){a=R[a];if(!a)throw new P(8);return a}var Fb={};function Gb(){if(!Hb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Fb)a[b]=Fb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Hb=c}return Hb}var Hb;
function Ib(a){return 0===a%4&&(0!==a%100||0===a%400)}function Jb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Kb=[31,29,31,30,31,30,31,31,30,31,30,31],Lb=[31,28,31,30,31,30,31,31,30,31,30,31];function Mb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ib(a.getFullYear())?Kb:Lb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Nb(a,b,c,d){function e(f,q,u){for(f="number"===typeof f?f.toString():f||"";f.length<q;)f=u[0]+f;return f}function h(f,q){return e(f,q,"0")}function k(f,q){function u(zb){return 0>zb?-1:0<zb?1:0}var B;0===(B=u(f.getFullYear()-q.getFullYear()))&&0===(B=u(f.getMonth()-q.getMonth()))&&(B=u(f.getDate()-q.getDate()));return B}function m(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function v(f){f=Mb(new Date(f.H+1900,0,1),f.W);var q=new Date(f.getFullYear()+1,0,4),u=m(new Date(f.getFullYear(),0,4));q=m(q);return 0>=k(u,f)?0>=k(q,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var p=K[d+40>>2];d={ta:K[d>>2],sa:K[d+4>>2],U:K[d+8>>2],R:K[d+12>>2],P:K[d+16>>2],H:K[d+20>>2],V:K[d+24>>2],W:K[d+28>>2],Ba:K[d+32>>2],ra:K[d+36>>2],
ua:p?ra(p):""};c=ra(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in p)c=c.replace(new RegExp(r,"g"),p[r]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");p={"%a":function(f){return x[f.V].substring(0,3)},"%A":function(f){return x[f.V]},"%b":function(f){return F[f.P].substring(0,3)},"%B":function(f){return F[f.P]},"%C":function(f){return h((f.H+1900)/100|0,2)},"%d":function(f){return h(f.R,2)},"%e":function(f){return e(f.R,2," ")},"%g":function(f){return v(f).toString().substring(2)},"%G":function(f){return v(f)},"%H":function(f){return h(f.U,2)},"%I":function(f){f=
f.U;0==f?f=12:12<f&&(f-=12);return h(f,2)},"%j":function(f){return h(f.R+Jb(Ib(f.H+1900)?Kb:Lb,f.P-1),3)},"%m":function(f){return h(f.P+1,2)},"%M":function(f){return h(f.sa,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.U&&12>f.U?"AM":"PM"},"%S":function(f){return h(f.ta,2)},"%t":function(){return"\t"},"%u":function(f){return f.V||7},"%U":function(f){var q=new Date(f.H+1900,0,1),u=0===q.getDay()?q:Mb(q,7-q.getDay());f=new Date(f.H+1900,f.P,f.R);return 0>k(u,f)?h(Math.ceil((31-u.getDate()+
(Jb(Ib(f.getFullYear())?Kb:Lb,f.getMonth()-1)-31)+f.getDate())/7),2):0===k(u,q)?"01":"00"},"%V":function(f){var q=new Date(f.H+1901,0,4),u=m(new Date(f.H+1900,0,4));q=m(q);var B=Mb(new Date(f.H+1900,0,1),f.W);return 0>k(B,u)?"53":0>=k(q,B)?"01":h(Math.ceil((u.getFullYear()<f.H+1900?f.W+32-u.getDate():f.W+1-u.getDate())/7),2)},"%w":function(f){return f.V},"%W":function(f){var q=new Date(f.H,0,1),u=1===q.getDay()?q:Mb(q,0===q.getDay()?1:7-q.getDay()+1);f=new Date(f.H+1900,f.P,f.R);return 0>k(u,f)?h(Math.ceil((31-
u.getDate()+(Jb(Ib(f.getFullYear())?Kb:Lb,f.getMonth()-1)-31)+f.getDate())/7),2):0===k(u,q)?"01":"00"},"%y":function(f){return(f.H+1900).toString().substring(2)},"%Y":function(f){return f.H+1900},"%z":function(f){f=f.ra;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.ua},"%%":function(){return"%"}};for(r in p)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),p[r](d)));r=Va(c,!1);if(r.length>b)return 0;I.set(r,a);return r.length-1}
function lb(a,b,c,d){a||(a=this);this.parent=a;this.L=a.L;this.T=null;this.id=eb++;this.name=b;this.mode=c;this.D={};this.F={};this.rdev=d}Object.defineProperties(lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ab();S=Array(4096);sb(Q,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Ta(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ub("/dev/null",259);Sa(1280,Wa);Sa(1536,Xa);ub("/dev/tty",1280);ub("/dev/tty1",1536);var a=Pa();W("random",a);W("urandom",a);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");sb({L:function(){var b=Za(a,"fd",16895,73);b.D={lookup:function(c,d){var e=R[+d];if(!e)throw new P(8);c={parent:null,L:{ia:"fake"},D:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();function Va(a,b){var c=Array(ua(a)+1);a=oa(a,c,0,c.length);b&&(c.length=a);return c}
var Qb={j:function(a){try{var b=Z(a);return V(b.path,b.flags,0).fd}catch(c){return"undefined"!==typeof X&&c instanceof P||D(c),-c.I}},p:function(a,b){try{var c=Z(a);if(c.fd===b)var d=b;else{var e=c.path,h=c.flags,k=R[b];k&&xb(k);d=V(e,h,0,b,b).fd}return d}catch(m){return"undefined"!==typeof X&&m instanceof P||D(m),-m.I}},d:function(a,b,c){Eb=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:V(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=
e,0;case 12:return e=Y(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return K[Ob()>>2]=28,-1;default:return-28}}catch(h){return"undefined"!==typeof X&&h instanceof P||D(h),-h.I}},h:function(a,b,c){Eb=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Y();return K[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.F.ma)throw new P(59);
return d.F.ma(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:D("bad ioctl syscall "+b)}}catch(h){return"undefined"!==typeof X&&h instanceof P||D(h),-h.I}},i:function(a,b,c){Eb=c;try{var d=ra(a),e=c?Y():0;return V(d,b,e).fd}catch(h){return"undefined"!==typeof X&&h instanceof P||D(h),-h.I}},e:function(){D()},l:function(a,b,c){pa.copyWithin(a,b,b+c)},m:function(){D("OOM")},o:function(a,b){try{var c=0;Gb().forEach(function(d,e){var h=b+c;e=K[a+4*e>>2]=h;for(h=0;h<d.length;++h)I[e++>>
0]=d.charCodeAt(h);I[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof X&&d instanceof P||D(d),d.I}},f:function(a,b){try{var c=Gb();K[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});K[b>>2]=d;return 0}catch(e){return"undefined"!==typeof X&&e instanceof P||D(e),e.I}},a:function(a){Pb(a)},b:function(a){try{var b=Z(a);xb(b);return 0}catch(c){return"undefined"!==typeof X&&c instanceof P||D(c),c.I}},g:function(a,b,c,d){try{a:{for(var e=Z(a),h=a=0;h<c;h++){var k=K[b+(8*h+
4)>>2],m=e,v=K[b+8*h>>2],p=k,r=void 0,x=I;if(0>p||0>r)throw new P(28);if(null===m.fd)throw new P(8);if(1===(m.flags&2097155))throw new P(8);if(16384===(m.node.mode&61440))throw new P(31);if(!m.F.read)throw new P(28);var F="undefined"!==typeof r;if(!F)r=m.position;else if(!m.seekable)throw new P(70);var f=m.F.read(m,x,v,p,r);F||(m.position+=f);var q=f;if(0>q){var u=-1;break a}a+=q;if(q<k)break}u=a}K[d>>2]=u;return 0}catch(B){return"undefined"!==typeof X&&B instanceof P||D(B),B.I}},k:function(a,b,c,
d,e){try{var h=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;yb(h,a,d);Ja=[h.position>>>0,(O=h.position,1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];K[e>>2]=Ja[0];K[e+4>>2]=Ja[1];h.Y&&0===a&&0===d&&(h.Y=null);return 0}catch(k){return"undefined"!==typeof X&&k instanceof P||D(k),k.I}},c:function(a,b,c,d){try{a:{for(var e=Z(a),h=a=0;h<c;h++){var k=e,m=K[b+8*h>>2],v=K[b+(8*h+4)>>2],p=void 0,
r=I;if(0>v||0>p)throw new P(28);if(null===k.fd)throw new P(8);if(0===(k.flags&2097155))throw new P(8);if(16384===(k.node.mode&61440))throw new P(31);if(!k.F.write)throw new P(28);k.seekable&&k.flags&1024&&yb(k,0,2);var x="undefined"!==typeof p;if(!x)p=k.position;else if(!k.seekable)throw new P(70);var F=k.F.write(k,r,m,v,p,void 0);x||(k.position+=F);try{if(k.path&&gb.onWriteToFile)gb.onWriteToFile(k.path)}catch(u){E("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+u.message)}var f=
F;if(0>f){var q=-1;break a}a+=f}q=a}K[d>>2]=q;return 0}catch(u){return"undefined"!==typeof X&&u instanceof P||D(u),u.I}},n:function(a,b,c,d){return Nb(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ka=g.asm.q;wa=e=ka.buffer;g.HEAP8=I=new Int8Array(e);g.HEAP16=xa=new Int16Array(e);g.HEAP32=K=new Int32Array(e);g.HEAPU8=pa=new Uint8Array(e);g.HEAPU16=new Uint16Array(e);g.HEAPU32=new Uint32Array(e);g.HEAPF32=new Float32Array(e);g.HEAPF64=new Float64Array(e);ya=g.asm.w;Aa.unshift(g.asm.r);L--;g.monitorRunDependencies&&g.monitorRunDependencies(L);0==L&&(null!==Ea&&(clearInterval(Ea),Ea=null),M&&(e=M,M=null,e()))}function b(e){a(e.instance)}function c(e){return Ia().then(function(h){return WebAssembly.instantiate(h,
d)}).then(e,function(h){E("failed to asynchronously prepare wasm: "+h);D(h)})}var d={a:Qb};L++;g.monitorRunDependencies&&g.monitorRunDependencies(L);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return E("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return G||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||N.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){E("wasm streaming compile failed: "+h);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.r).apply(null,arguments)};g._translate=function(){return(g._translate=g.asm.s).apply(null,arguments)};g._highlight=function(){return(g._highlight=g.asm.t).apply(null,arguments)};g._main=function(){return(g._main=g.asm.u).apply(null,arguments)};
g._API=function(){return(g._API=g.asm.v).apply(null,arguments)};var Ob=g.___errno_location=function(){return(Ob=g.___errno_location=g.asm.x).apply(null,arguments)},bb=g._malloc=function(){return(bb=g._malloc=g.asm.y).apply(null,arguments)},qa=g.stackSave=function(){return(qa=g.stackSave=g.asm.z).apply(null,arguments)},sa=g.stackRestore=function(){return(sa=g.stackRestore=g.asm.A).apply(null,arguments)},H=g.stackAlloc=function(){return(H=g.stackAlloc=g.asm.B).apply(null,arguments)};g.ccall=na;
g.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(h){return"number"===h});return"string"!==b&&e&&!d?ma(a):function(){return na(a,b,c,arguments,d)}};var Rb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}M=function Sb(){Rb||Tb();Rb||(M=Sb)};
function Tb(a){function b(){if(!Rb&&(Rb=!0,g.calledRun=!0,!la)){g.noFSInit||Bb||(Bb=!0,Ab(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?W("stdin",g.stdin):vb("/dev/tty","/dev/stdin"),g.stdout?W("stdout",null,g.stdout):vb("/dev/tty","/dev/stdout"),g.stderr?W("stderr",null,g.stderr):vb("/dev/tty1","/dev/stderr"),V("/dev/stdin",0),V("/dev/stdout",1),V("/dev/stderr",1));Ka(Aa);fb=!1;Ka(Ba);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ub){var c=a,d=g._main;c=c||[];var e=c.length+
1,h=H(4*(e+1));K[h>>2]=va(aa);for(var k=1;k<e;k++)K[(h>>2)+k]=va(c[k-1]);K[(h>>2)+e]=0;try{var m=d(e,h);Pb(m,!0)}catch(v){v instanceof ia||"unwind"==v||((c=v)&&"object"===typeof v&&v.stack&&(c=[v,v.stack]),E("exception thrown: "+c),w(1,v))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ca.unshift(c);Ka(Ca)}}a=a||t;if(!(0<L)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Da();Ka(za);0<L||(g.setStatus?
(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Tb;function Pb(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);la=!0}w(a,new ia(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ub=!0;g.noInitialRun&&(Ub=!1);Tb();
