name: diagon
version: '1.0'
summary: Ascii art generators from markdown-style expression.
description: |
  Diagon is an interactive interpreter. It transforms markdown-style expression
  into an ascii-art representation.
  It is written in C++ and use WebAssembly, HTML and CSS to make a Web
  Application. It can be used at https://arthursonzogni.com/Diagon.  It can also
  be used in script as a 'normal' application.

grade: stable
confinement: strict
icon: ./favicon.png

apps:
  diagon:
    command: diagon

parts:
  diagon:
    plugin: cmake
    source: .
    build-packages:
      - unzip
      - curl

passthrough:
  title: Diagon
  license: MIT
