name: diagon
adopt-info: diagon
summary: Ascii art generators from markdown-style expression.
description: |
  Diagon is an interactive interpreter. It transforms markdown-style expression
  into an ascii-art representation.
  It is written in C++ and use WebAssembly, HTML and CSS to make a Web
  Application. It can be used at https://arthursonzogni.com/Diagon.  It can also
  be used in script as a 'normal' application.
grade: stable
confinement: strict
icon: "./favicon.png"
apps:
  diagon:
    command: diagon
base: core18
parts:
  diagon:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/Diagon
    source-type: git
    source-depth: 1
    build-snaps: [cmake/latest/edge] # We need a modern cmake.
    build-packages:
    - pkg-config
    - unzip
    - curl
    - uuid-dev
    - openjdk-8-jdk
    - libboost-graph-dev
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install
      snapcraftctl set-version "$(git rev-list --count HEAD)"

passthrough:
  title: Diagon
  license: MIT

